version: '3.8'

services:
  text-clustering-app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: text-clustering-streamlit
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - MEMORY_LIMIT=2GB
      - STREAMLIT_SERVER_ENABLE_CORSE=false
      - CLUSTERING_TEMP_DIR=/app/temp
    command: >
      streamlit run main.py
      --server.port=8502
      --server.address=0.0.0.0
      --server.headless=true
      --server.enableXsrfProtection=false
      --server.enableCORS=false
      --logger.level=debug
      --browser.serverAddress="lrec2026.myaddr.tools"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

volumes:
  app_data:
  app_logs:
